# List available recipes
help:
    just -l

# Install tool dependencies
deps:
    #!/bin/bash
    if ! hash wasm-opt 2>/dev/null; then
        cargo install wasm-opt
    fi

# Downloads
@build: deps
    just get-models
    cargo build --target wasm32-wasi --release
    wasm-opt -Oz target/wasm32-wasi/release/tract-object-detection.wasm -o target/wasm32-wasi/release/shrunk.wasm
    mv target/wasm32-wasi/release/shrunk.wasm target/wasm32-wasi/release/tract-object-detection.wasm
    echo 👍 Done

@get-models:
    mkdir -p models
    wget --continue --quiet https://storage.googleapis.com/mobilenet_v2/checkpoints/mobilenet_v2_1.4_224.tgz --output-document $TMPDIR/mobilenet_v2_1.4_224.tgz
    tar zxf $TMPDIR/mobilenet_v2_1.4_224.tgz -C models

@run:
    just get-models
    cargo run $@
